# Generated by Django 4.2 on 2023-04-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('optimized_circuit', models.CharField(max_length=300)),
                ('circuits', models.CharField(max_length=300)),
                ('result', models.JSONField()),
            ],
        ),
    ]
